project:
  type: website

website:
  title: "Finist'R 2023"
  navbar:
    left:
      - icon: github
        href: https://github.com/StateOfTheR/finistR2023
        aria-label: GitHub
      - text: "Instructions"
        href: instructions.qmd
    right:
      - text: workflow
        menu:
        - text: inla
          href: R_INLA.qmd
        aria-label: GitHub
      - text: torch (R vs Py)
        menu: 
          - torch_test-brulee.qmd
          - torch_Python_regression.qmd
          - torch_R_PLN.qmd
          - torch_Python-PLN.qmd
          - torch_Python_R_ResNet.qmd
        aria-label: GitHub



format:
  html:
    theme: flatly
    highlight: tango
    toc: true
    
