project:
  type: website

website:
  title: "Finist'R 2023"
  navbar:
    left:
      - icon: github
        href: https://github.com/StateOfTheR/finistR2023
        aria-label: GitHub
      - text: "Instructions"
        href: instructions.qmd
<<<<<<< HEAD
    right:
      - text: Enseignement
        menu:
        - text: Learnr
          href: teaching.qmd
        aria-label: GitHub
      - text: Workflow
        menu:
        - text: Issue - Reprex
          href: issue_reprex.qmd
        aria-label: GitHub
      - text: Analyse statistique
        menu:
        - text: Inla
          href: R_INLA.qmd
        - text: Tidymodels
          href: tidymodels_build_new_model.qmd
        aria-label: GitHub
      - text: torch (R vs Py)
        menu: 
          - torch_test-brulee.qmd
          - torch_Python_R_ResNet.qmd
          - torch_Python-regression.qmd
          - torch_R-PLN.qmd
          - torch_Python-PLN.qmd
=======
    left:
      - text: workflow
        href: https://github.com/StateOfTheR/finistR2023
        aria-label: GitHub
      - text: inla
<<<<<<< HEAD
        href: RINLA.qmd
>>>>>>> f04efc2 (add link to inla)
=======
        href: R_INLA.qmd
>>>>>>> b12ca05 (Correct ref to R_INLA)
        aria-label: GitHub



format:
  html:
    theme: flatly
    highlight: tango
    toc: true
    
