---
title: "Nouveautés {learnr} et {exams}"
format: html
toc: true
author: 
  - Pierre Barbillon
  - Marie-Pierre Etienne
  - Isabelle Sanchez
date: 24/08/2023
---

# Introduction

Nous allons ici discuter du package {exams} qui permet de créer  des feuilles d'examens (papier ou en ligne).

# exams

{exams} est un package R disponible sur le CRAN. Il permet de construire des examens de manière automatique au format markdown ou LaTeX et incluant des chunks de code R dynamique. Comme pour learnr les exercices peuvent être à choix multiples ou simples, des problèmes arithmétiques, du code…

<https://www.r-exams.org/>

Un examen exams a plusieurs sorties possibles:

* fichiers autonomes : PDF, HTML, Docx, ODT, ...
* fichiers dynamiques: **Moodle XML**, QTI 1.2, QTI 2.1, Blackboard, Canvas, OpenOLAT, ARSnova, and TCExam
    
Il est possible **de scanner les feuilles d’examens imprimés** et de les évaluer automatiquement avec l'outil **NOPS**.

Une autre option intéressante, pour réduire le risque de triche, exams propose un mécanisme de variations aléatoires des exercices:

* mélange de l’ordre des questions
* mélange des réponses possibles pour les QCMs
* mélange des données des exercices

Il est également possible de combiner {exams} avec un tutoriel {learnr}: <https://www.r-exams.org/tutorials/exams2learnr/>.

# Références

1. https://www.r-exams.org/
2. https://www.r-exams.org/tutorials/
3. https://www.r-exams.org/intro/dynamic/

