using Pkg
Pkg.add("IJulia")
Pkg.add("GeoDataFrames")
Pkg.add("Distributed")
Pkg.add("StatsAPI")
Pkg.add("Plots")
Pkg.add("DelimitedFiles")
Pkg.add("DataFrames")
Pkg.add("CSV")
Pkg.add("GeoStats")
Pkg.add("Rasters")
Pkg.add("Shapefile")
Pkg.add("GeoTables")
Pkg.add("CairoMakie")
Pkg.add("WGLMakie")
