name: website
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build website with rmarkdown
    runs-on: ubuntu-latest
    # container: registry.forgemia.inra.fr/theodore.vanrenterghem/docker-finistr:0.0.4
    steps:
      - name: free disk space
        run: |
          sudo swapoff /swapfile
          sudo rm -rf /swapfile /usr/share/dotnet /usr/local/lib/android /opt/ghc
      - name: install new docker
        run: |
          docker run registry.forgemia.inra.fr/theodore.vanrenterghem/docker-finistr:0.0.4
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Generate slides
        run: "quarto render"
      - name: GitHub Pages action
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
