name: website
on:
  push:
    branches:
      - master

jobs:   
  build:
    name: Build website with rmarkdown
    runs-on: ubuntu-latest
    container: stateofther/r-finistr2022:0.12


    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Generate slides
        run: Rscript -e "rmarkdown::render_site(encoding = 'UTF-8')"
      - name: Generate quarto page
        run: |
          quarto render QuartoTest.qmd --to html
          cp QuartoTest.html build/.
          cp -R QuartoTest_files build/.
      - name: GitHub Pages action
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
