name: website
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      - name: Delete huge unnecessary tools folder
        run: rm -rf /opt/hostedtoolcache
      - name Build website with rmarkdown
        uses: registry.forgemia.inra.fr/theodore.vanrenterghem/docker-finistr:0.0.5
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Generate slides
        run: "quarto render"
      - name: GitHub Pages action
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
